name: Client Staging Deployment

on:
  push:
    branches:
      - staging

jobs:
  publish:
    name: Publish Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get Smart Tag
        id: prepare
        uses: Surgo/docker-smart-tag-action@v1
        with:
          docker_image: ${{ secrets.DOCKER_USERNAME }}/optimabalita-client
      - name: Buld and Push Image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.prepare.outputs.tag }}

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Setup gcloud CLI
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: optimabalita-stage
          location: asia-southeast2-c
      - name: Restart Deployment
        run: kubectl rollout restart deployment optimabalita-client-depl