name: Client Staging Deployment

on:
  push:
    branches:
      - staging

jobs:
  publish:
    name: Publish Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get Smart Tag
        id: prepare
        uses: Surgo/docker-smart-tag-action@v1
        with:
          docker_image: ${{ secrets.DOCKER_USERNAME }}/optimabalita-client
          tag_with_sha: true
      - name: Build and Push Image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.prepare.outputs.tag }}
      - name: Publish Tag as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-tag
          path: ${{ steps.prepare.outputs.tag }}

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Setup gcloud CLI
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: optimabalita-stage
          location: asia-southeast2-c
      - name: Get Docker Tag
        uses: actions/download-artifact@v2
        with:
          name: docker-tag
      - name: Read Docker Tag
        id: read-docker-tag
        run: echo ::set-output name=docker-tag::$(cat docker-tag)
      - name: Set New Image in K8s Deployment
        run: kubectl set image deployment/optimabalita-client-depl optimabalita-client=${{ steps.read-docker-tag.outputs.docker-tag }}