name: Client Staging Deployment

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/optimabalita-client .
      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to Docker Hub Registry
        run: docker push ${{ secrets.DOCKER_USERNAME }}/optimabalita-client
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save optimabalita-staging
      - name: Restart Deployment
        run: kubectl rollout restart deployment optimabalita-client-depl