name: Client Staging Deployment

on:
  push:
    branches:
      - staging

jobs:
  publish:
    name: Publish Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/optimabalita-client .
      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to Docker Hub Registry
        run: docker push ${{ secrets.DOCKER_USERNAME }}/optimabalita-client

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Setup gcloud CLI
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: optimabalita-stage
          location: asia-southeast1-a
      - name: Restart Deployment
        run: kubectl rollout restart deployment optimabalita-client-depl